#!/bin/bash

rm -f waves.cpp
echo "// generated by makewaves.sh" >> waves.cpp

xxd -i BASS1.wav >> waves.cpp
xxd -i BASS2.wav >> waves.cpp
xxd -i HAT1.wav >> waves.cpp
xxd -i HAT2.wav >> waves.cpp
xxd -i SNARE1.wav >> waves.cpp
xxd -i SYMBAL1.wav >> waves.cpp
